---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-deployment-p9
spec:
  accessModes:
    - ReadWriteMany  # In this example, multiple Pods consume the same PVC.
  resources:
    requests:
      storage: 10Gi
  storageClassName: p9-csi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-p9
spec:
  replicas: 3
  selector:
    matchLabels:
        name: deployment-p9
  template:
    metadata:
        name: deployment-p9
        labels:
            name: deployment-p9
    spec:
      containers:
      containers:
      - name: deployment-p9
        image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
        command:
          - "/bin/sh"
          - "-c"
          - while true; do echo $(hostname) $(date) >> /mnt/p9/outfile; sleep 1; done
        volumeMounts:
          - name: p9
            mountPath: "/mnt/p9"
      volumes:
      - name: p9
        persistentVolumeClaim:
          claimName: pvc-deployment-p9
