---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-p9
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - p9vers=4.1
  csi:
    driver: p9.csi.k8s.io
    readOnly: false
    volumeHandle: unique-volumeid  # make sure it's a unique id in the cluster
    volumeAttributes:
      server: p9-server.default.svc.cluster.local
      share: /
