---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-p9-static
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-p9
  storageClassName: ""
