---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: p9-csi
provisioner: p9.csi.k8s.io
parameters:
  server: p9-server.default.svc.cluster.local
  share: /
reclaimPolicy: Retain  # only retain is supported
volumeBindingMode: Immediate
mountOptions:
  - hard
  - p9vers=4.1
