image:
    p9:
        repository: gcr.io/k8s-staging-sig-storage/p9plugin
        tag: amd64-linux-canary
        pullPolicy: IfNotPresent
    csiProvisioner:
        repository: k8s.gcr.io/sig-storage/csi-provisioner
        tag: v2.0.4
        pullPolicy: IfNotPresent
    livenessProbe:
        repository: k8s.gcr.io/sig-storage/livenessprobe
        tag: v2.1.0
        pullPolicy: IfNotPresent
    nodeDriverRegistrar:
        repository: k8s.gcr.io/sig-storage/csi-node-driver-registrar
        tag: v2.0.1
        pullPolicy: IfNotPresent
serviceAccount:
  create: true
rbac:
  create: true
controller:
  replicas: 2
